export const content = {
  "brand.title": `Sunscreen Research`,
  "brand.sub": `Formulation Chemistry & Regulatory Review`,
  "hero.meta1": `<svg class="icon-sm" viewBox="0 0 24 24" stroke-width="1.5" fill="none" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></svg> Updated: August 2026`,
  "hero.meta2": `<svg class="icon-sm" viewBox="0 0 24 24" stroke-width="1.5" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7z"/><circle cx="12" cy="12" r="3"/></svg> Reading time: approx. 18 minutes`,
  "hero.meta3": `<svg class="icon-sm" viewBox="0 0 24 24" stroke-width="1.5" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><path d="M14 2v6h6M16 13H8M16 17H8M10 9H8"/></svg> Sources: 22`,
  "hero.kicker": `Formulation Chemistry & Regulatory Analysis`,
  "hero.title": `The SPF number printed on your sunscreen — <em>how much of it holds in the real world?</em>`,
  "hero.p1": `In Bangladesh's climate — where the UV Index routinely exceeds 10, temperatures surpass 35°C, and humidity remains above 80% — the figure printed on a sunscreen label and the actual protection delivered to skin can diverge substantially. How large is that gap? <strong>Of 30 commercially available sunscreens collected from the Bangladeshi market, 93.3% failed to meet their labelled SPF claims.</strong>`,
  "hero.p2": `This report examines why that failure occurs — through the lens of formulation chemistry — and provides a comparative analysis of how regulatory frameworks across different jurisdictions address the underlying problem. Every claim is accompanied by a source reference.`,
  "hero.abstractLabel": `Abstract`,
  "hero.abstract": `The sophistication of a sunscreen's UV filters accounts for only half of its real-world protective capacity. The other half depends on whether the film those filters are carried in — the layer formed on the skin's surface — remains intact under perspiration, sebum, and heat. This report distinguishes between these two distinct failure modes and compares how different regulatory frameworks address the second.`,
  "hero.byline.name": `Naeem Muhammad`,
  "hero.byline.stat1": `180 days of research`,
  "hero.byline.stat2": `100+ sources`,
  "hero.scroll": `Read the research`,
  "hero.cta": `Read the Research`,
  "ui.chartHint": `Tap a bar for details`,
  "ui.chartPlaceholder": `Chart loading`,
  "toc.label": `Contents`,
  "toc.1": `Two Distinct Problems`,
  "toc.2": `Regulatory Comparison`,
  "toc.3": `The Numbers`,
  "toc.4": `Long-Term Effects`,
  "toc.5": `Skin Science`,
  "toc.6": `Selection Framework`,
  "toc.7": `References`,
  "toc.8": `Special Report`,
  "toc.realworld": `Illustrative Example`,
  "s1.eyebrow": `The Core Problem`,
  "s1.title": `One number — but two entirely different questions`,
  "s1.lead": `The SPF value on a sunscreen label is a measurement obtained under controlled laboratory conditions. The real question is whether that same result holds on a street in Bangladesh — in heat, in sunlight, and in sweat. This section explains why the answer is not always yes.`,
  "s1.guide": `After reading this section, you will understand why a sunscreen with an excellent filter can still fail to protect in practice — and why that failure has nothing to do with the quality of the filter itself. In other words, a superior filter and superior film do not automatically guarantee superior protection.`,
  "s1.card1.title": `Question One — Photostability`,
  "s1.card1.text": `When UV light strikes a sunscreen filter, does the filter molecule degrade — or does it remain intact? Modern filters such as Bemotrizinol (Tinosorb S) and DHHB (Uvinul A Plus) are genuinely photostable: they absorb UV radiation and return to their ground state without chemical degradation. The reverse process — progressive loss of efficacy under UV exposure — is termed photodegradation. However, photostability alone does not tell the full story. Even a modern, photostable filter cannot protect skin if the sunscreen film carrying it has been washed away by sweat. The filter may be chemically intact, but if the film layer has lifted from the skin, that filter can no longer provide meaningful protection.`,
  "s1.card1.foot": `Source: Chaudhuri, Int J Cosmet Sci, 2001`,
  "s1.card2.title": `Question Two — Film Durability`,
  "s1.card2.text": `Regardless of how photostable a filter is, the question remains: does the film formed on the skin actually persist? If that film is washed away or thinned by perspiration, protection diminishes. In Bangladesh's climate — temperatures exceeding 35°C, humidity above 80%, and heavy sweating — how long that film remains intact is the critical variable. And film durability is not determined by the filter alone; the film-forming polymers and emulsion architecture play an equally important role. Put plainly: a superior filter is necessary but not sufficient. The film layer must also hold — and that must be demonstrable.`,
  "s1.card2.foot": `Source: Keshavarzi et al., Skin Res Technol, 2022`,
  "s1.card3.title": `The Formulation Dilemma`,
  "s1.card3.text": `In pursuit of a lightweight skin feel, formulators frequently reduce the concentration of film-forming polymers — the ingredients responsible for creating and sustaining the thin protective layer on skin. These polymers are also what prevents the sunscreen film from being displaced by sweat or water. The design choice that makes a sunscreen feel invisible is often the same choice that compromises its real-world durability.`,
  "s1.card3.foot": `Source: US Patent 5041281A; Cosmetics & Toiletries Journal`,
  "s1.note.head": `The physics — why even an excellent filter can lose to sweat`,
  "s1.note.body": `UV attenuation follows the Beer-Lambert law: A(λ) = ε·c·d, where "d" is film thickness. But the film deposited on skin is never perfectly uniform — follicles, folds, and surface irregularities create variation. Ferrero and Sohn have demonstrated that when sweat causes the film to dewet — contracting into discrete islands — certain areas approach near-zero thickness. UV penetrates these areas disproportionately. The consequence: without any chemical degradation of the filter, purely through geometric redistribution of the film, an SPF 50 sunscreen can functionally perform at SPF 5.`,
  "s1.note.cite": `Ferrero, L. & Sohn, M. — "Generalized Beer-Lambert Law for Evaluating Heterogeneous Sunscreen Films" — ACS Nano Letters, 2024`,
  "s1.bd.head": `The problem documented in Bangladesh's own market`,
  "s1.bd.body": `This is not a theoretical concern drawn from foreign research alone. Direct evidence has been documented in the Bangladeshi market. A 2026 study independently tested 30 popular sunscreen products collected from the local market. The findings were concerning: 93.3% of products tested delivered lower protection than their labelled SPF claims. The film durability and regulatory gaps described in this report are not distant or abstract problems — they are a daily reality for Bangladeshi consumers.`,
  "s1.bd.cite": `Source: Haque et al., Journal of Biosciences and Public Health, 2026; 2(3):264–277`,
  "s2.eyebrow": `Sunscreen Regulation & Science`,
  "s2.title": `A Comparative Analysis of Regulatory Frameworks`,
  "s2.lead": `Where a sunscreen is regulated — and how — matters. Different jurisdictions impose markedly different standards: some require rigorous pre-market testing, others mandate specific water resistance protocols, and they differ considerably in manufacturing standards and in what happens when a product fails. The data below are drawn directly from each country's official regulatory documentation.`,
  "s2.guide": `Australia's column is highlighted in green in the table below. It is the only framework in this comparison with documented, active post-market surveillance — evidence of which is presented immediately below the table. By contrast, post-market oversight in the South Asian subcontinent is comparatively limited.`,
  "s2.tbl.criterion": `Regulatory Criterion`,
  "s2.tbl.au": `Australia`,
  "s2.tbl.jp": `Japan`,
  "s2.tbl.eu": `European Union`,
  "s2.tbl.kr": `South Korea`,
  "s2.tbl.in": `India`,
  "s2.r1.label": `Product Classification`,
  "s2.r1.au": `Therapeutic Medicine`,
  "s2.r1.jp": `Quasi-Drug`,
  "s2.r1.eu": `Cosmetic (strict EU regulation)`,
  "s2.r1.kr": `Functional Cosmetic`,
  "s2.r1.in": `Schedule S Cosmetic`,
  "s2.r2.label": `Pre-Market SPF Testing`,
  "s2.r2.au": `Mandatory (ISO 24444)`,
  "s2.r2.jp": `Mandatory (JCIA standard)`,
  "s2.r2.eu": `Mandatory (Cosmetics Europe)`,
  "s2.r2.kr": `Prerequisite for approval`,
  "s2.r2.in": `Static test at registration (once)`,
  "s2.r3.label": `Water Resistance Test Duration`,
  "s2.r3.au": `Up to 240 minutes (4 hours)`,
  "s2.r3.auSub": `Per ISO 16217 + 18861`,
  "s2.r3.jp": `Up to 80 minutes (★★)`,
  "s2.r3.jpSub": `Per ISO 18861:2020`,
  "s2.r3.eu": `80 minutes (very water resistant)`,
  "s2.r3.kr": `No specific mandatory duration`,
  "s2.r3.in": `No mandatory water resistance standard`,
  "s2.r4.label": `Manufacturing Standard (GMP)`,
  "s2.r4.au": `Pharmaceutical-grade (PIC/S)`,
  "s2.r4.jp": `High standard (Quasi-Drug GMP)`,
  "s2.r4.eu": `Cosmetic GMP (ISO 22716)`,
  "s2.r4.kr": `Major ODM lab standard (Kolmar, Cosmax)`,
  "s2.r4.in": `General cosmetic-grade`,
  "s2.r5.label": `Post-Market Surveillance`,
  "s2.r5.au": `Active and routine — government-operated`,
  "s2.r5.jp": `Robust — rapid response to identified issues`,
  "s2.r5.eu": `Strong — EU-wide market surveillance`,
  "s2.r5.kr": `Moderate — significantly strengthened post-2020`,
  "s2.r5.in": `Limited — no SPF-related recalls documented in public records`,
  "s2.r6.label": `Primary Reference Standards`,
  "s2.r6.au": `AS/NZS 2604:2021 · ISO 24444 · ISO 16217 · ISO 18861`,
  "s2.r6.jp": `JCIA Guidelines · ISO 24444 · ISO 18861 (2022–2027 implementation)`,
  "s2.r6.eu": `Cosmetics Europe Guidelines · EU Regulation 1223/2009`,
  "s2.r6.kr": `MFDS Functional Cosmetic Regulation · ISO 24444`,
  "s2.r6.in": `CDSCO Cosmetics Rules 2020 · BIS IS 4707:2022`,
  "s2.caption": `All data sourced from official regulatory documentation. Sources: TGA Australian Regulatory Guidelines for Sunscreens (ARGS); AS/NZS 2604:2021; MHLW Pharmaceutical and Medical Device Act; JCIA Guidelines; MFDS Functional Cosmetics Regulation; CDSCO Cosmetics Rules 2020; BIS IS 4707:2022; ISO 24444:2019; ISO 18861:2020.`,
  "s2.au.head": `A documented case study in active regulatory enforcement`,
  //"s2.au.sub1.num": `01`,
  "s2.au.sub1.title": `AUSTRALIA'S SUNSCREEN SCANDAL`,
  "s2.au.body1": `Australia's regulatory oversight of sunscreen products is among the most active in the world. In June 2025, when the independent consumer organisation CHOICE published test results indicating that several commercially available sunscreens had failed to meet their labelled SPF claims, the Therapeutic Goods Administration (TGA) initiated a formal investigation within days. The incident was covered by Australia's national broadcaster and widely referred to as "Australia's sunscreen scandal." The regulatory response was decisive: nineteen products sharing a common base formulation were officially recalled from the market and had their licences revoked. In March 2026, the TGA proposed further tightening, including mandatory laboratory accreditation requirements and standardised data submission obligations for manufacturers.`,
  //"s2.au.sub2.num": `02`,
  "s2.au.sub2.title": `La Roche-Posay UVMune 400`,
  "s2.au.body2": `The La Roche-Posay Anthelios UVMune 400 is widely regarded as one of the most scientifically advanced sunscreen formulations currently available, representing approximately a decade of R&D. In 2022, L'Oréal introduced the UVMune 400 technology, with La Roche-Posay Anthelios becoming the first brand to market it. Its central innovation is the Mexoryl 400 filter, engineered to protect against ultra-long UVA radiation in the 380–400 nanometre range — a band that most conventional filters address inadequately.

While available internationally from 2022, its entry into the Australian market required compliance with Australia's distinct regulatory framework, under which sunscreens are classified as Therapeutic Goods. This reflects the severity of UV-related health risks in Australia: approximately two in three Australians will be diagnosed with skin cancer at some point in their lifetime, with an estimated 1.6 to 1.8 million new cases annually and an overall case fatality rate of 0.1–0.2%.

Australia's Therapeutic Goods Administration conducts routine post-market surveillance — collecting products from retail shelves and subjecting them to unannounced laboratory testing. The joint Australia–New Zealand testing standard AS/NZS 2604 has been recognised as a reference benchmark by the standards bodies of more than 60 countries, and is consistently cited as a global gold standard in sunscreen regulation.`,
  "s2.au.cite": `Source: CHOICE Australia, June 2025; Therapeutic Goods Administration official statements, September 2025 & March 2026; CHP Australia`,
  "s3.eyebrow": `The Data`,
  "s3.title": `What the numbers actually show`,
  "s3.lead": `The two charts below are approximate illustrations derived from published, peer-reviewed research. They are not brand-specific claims or clinical predictions — they are a means of visualising trends documented in the scientific literature.`,
  "s3.guide": `The first chart illustrates how rapidly protection diminishes when sunscreen is applied in quantities below the test standard. The second shows the maximum water resistance test durations mandated by different regulatory frameworks.`,
  "s3.c1.title": `Application quantity and actual protection`,
  "s3.c1.sub": `Laboratory SPF testing uses 2.0 mg/cm² of sunscreen. In practice, most people apply considerably less — approximately 0.4 to 1.0 mg/cm². When quantity decreases, protection does not decline proportionally; it falls far more steeply.`,
  "s3.c1.note": `Source: Petersen & Wulf, Photodermatology Photoimmunology & Photomedicine, 2014 (PubMed 24313722) — dose-response power-function model`,
  "s3.c2.title": `Maximum water resistance test duration by regulatory framework`,
  "s3.c2.sub": `This chart shows the maximum duration for which sunscreens claiming water resistance are tested under immersion in different jurisdictions. Bangladesh and India have no dedicated national water resistance standard for sunscreens.`,
  "s3.c2.note": `Source: TGA AS/NZS 2604:2021; JCIA ISO 18861:2020 Guidelines; EU Cosmetics Europe Convention; CDSCO Cosmetics Rules 2020`,
  "s4.eyebrow": `Long-Term Effects`,
  "s4.title": `The cumulative impact of years of sunscreen use — or inadequate use`,
  "s4.lead": `Sunscreen's effects are not immediately visible. An absence of sunburn does not confirm protection, just as mild daily UV exposure does not produce an immediate signal. The real damage accumulates invisibly, day by day. Melasma, photoageing, and permanent structural changes to skin typically manifest five to ten years later — by which point reversal is no longer straightforward. Sunscreen is therefore a long-term investment: even when no difference is observable today, consistent daily use is shaping the skin of the future.`,
  "s4.guide": `The two charts below illustrate cumulative damage trajectories for UVA and UVB exposure respectively. Each shows three lines — High Quality, Mixed Quality, and Low Quality sunscreen — tracking relative damage accumulation over years of use. The higher the line, the more damage has accumulated.`,
  "s4.leg1": `High Quality (TGA) — consistent, high water-resistance protection`,
  "s4.leg2": `Mixed Quality — general use`,
  "s4.leg3": `Low Quality — weak film durability or inconsistent batch quality`,
  "s4.leg1s": `High Quality`,
  "s4.leg2s": `Mixed Quality`,
  "s4.leg3s": `Low Quality`,
  "s4.uva.title": `UVA Damage — cumulative accumulation over time`,
  "s4.uva.sub": `UVA radiation penetrates to the dermal layer, degrading collagen and contributing to melasma formation. This damage is minor on any given day, but accumulates progressively over years.`,
  "s4.uva.note": `Source: Approximate relative index derived from Petersen & Wulf (2014) dose-response model and published UVA penetration data`,
  "s4.uvb.title": `UVB Damage — cumulative accumulation over time`,
  "s4.uvb.sub": `UVB radiation damages the epidermal layer and causes direct DNA injury. It is most strongly associated with skin cancer.`,
  "s4.uvb.note": `Source: Approximate relative index derived from Petersen & Wulf (2014) dose-response model and published UVB exposure data`,
  "s4.note": `These figures represent an approximate relative index constructed from the Petersen & Wulf (2014) dose-response model and published data on film degradation under perspiration. They are not clinical outcome predictions for any specific individual.`,
  "s4.uv.label": `UVA and UVB — two distinct threats`,
  "s4.uv.b.name": `The sunburn ray`,
  "s4.uv.b.list": `<li>Causes skin reddening and sunburn.</li><li>Damages the epidermis (outermost skin layer).</li><li>Causes direct DNA strand breaks.</li><li>Primary driver of skin cancer.</li><li>The radiation measured by SPF.</li>`,
  "s4.uv.b.reach": `Skin penetration depth: to the epidermis`,
  "s4.uv.a.name": `The silent damage ray`,
  "s4.uv.a.list": `<li>Does not cause sunburn — damage is imperceptible.</li><li>Penetrates to the dermis (deep skin layer).</li><li>Degrades collagen — causes wrinkles and skin laxity.</li><li>Primary cause of melasma and persistent pigmentation.</li><li>Penetrates window glass into indoor environments.</li>`,
  "s4.uv.a.reach": `Skin penetration depth: to the dermis (substantially deeper than UVB)`,
  "s4.uv.note": `Approximately 95% of solar UV reaching the Earth's surface is UVA; 5% is UVB. UVA arrives consistently throughout the day, across all seasons, and through cloud cover. SPF measures protection against UVB only — a separate PA+++ or UVA-PF rating is required to assess UVA protection.`,
  "s4b.button": `CLICK HERE`,
  "s4b.eyebrow": `Illustrative Example`,
  "s4b.legend.a": `Naeema (TGA)`,
  "s4b.legend.b": `Mim`,
  "s4b.swipeHint": `Slide to explore`,
  "s4b.dot1": `0`,
  "s4b.dot2": `6mo`,
  "s4b.dot3": `1yr`,
  "s4b.dot4": `5`,
  "s4b.dot5": `10`,
  "s4b.dot6": `20`,
  "s4b.cardA.name": `Naeema`,
  "s4b.cardA.detail1": `Dhaka · Age 28`,
  "s4b.cardA.detail2": `Sunscreen: TGA-approved SPF 50+`,
  "s4b.cardA.detail3": `Water resistance: 80 minutes`,
  "s4b.cardA.detail4": `Film durability: High`,
  "s4b.cardB.name": `Mim`,
  "s4b.cardB.detail1": `Dhaka · Age 28`,
  "s4b.cardB.detail2": `Sunscreen: Commercially popular brand`,
  "s4b.cardB.detail3": `Labelled SPF: 50`,
  "s4b.cardB.detail4": `Film durability: Low`,
  "s4b.cardsIntro": `Both apply sunscreen every day.\nThe only difference — which one.`,
  "s4b.axis.y": `Relative skin damage`,
  "s4b.axis.x1": `0`,
  "s4b.axis.x2": `6mo`,
  "s4b.axis.x3": `1yr`,
  "s4b.axis.x4": `5`,
  "s4b.axis.x5": `10`,
  "s4b.axis.x6": `20`,
  "s4b.gap.label": `Damage gap`,
  "s4b.stage1.heading": `Day 0`,
  "s4b.stage1.body": `Both start from the same baseline. No visible difference is yet apparent.`,
  "s4b.stage2.heading": `6 Months`,
  "s4b.stage2.body": `Biological changes are beginning in Mim's skin — but the mirror still looks the same.`,
  "s4b.stage2.source": `PubMed 25660807`,
  "s4b.stage3.heading": `1 Year`,
  "s4b.stage3.body": `Clinical measurements detect a divergence. Mim is not yet aware.`,
  "s4b.stage3.source": `PubMed 27749441`,
  "s4b.stage4.heading": `5 Years`,
  "s4b.stage4.body": `The Nambour trial found 24% less skin ageing in daily sunscreen users after 4.5 years.`,
  "s4b.stage4.source": `PubMed 23732711`,
  "s4b.stage5.heading": `10 Years`,
  "s4b.stage5.body": `Mim notices the first visible signs — fine lines, pigmentation. Naeema's skin still looks much as it did.`,
  "s4b.stage5.source": `PubMed 23732711`,
  "s4b.stage6.heading": `20 Years`,
  "s4b.stage6.body": `The divergence is now clearly visible in the mirror. Both applied sunscreen every day.`,
  "s4b.assumptions.title": `Assumptions underlying this model`,
  "s4b.assumptions.item1": `Daily sunscreen use`,
  "s4b.assumptions.item2": `Adequate quantity applied each time`,
  "s4b.assumptions.item3": `Reapplication as required`,
  "s4b.assumptions.item4": `Equivalent overall UV exposure`,
  "s4b.assumptions.item5": `Both spend the majority of time indoors`,
  "s4b.assumptions.item6": `Equivalent outdoor exposure patterns`,
  "s4b.assumptions.item7": `Broadly similar sweat and water exposure`,
  "s4b.assumptions.item8": `Equivalent other photoprotection habits`,
  "s4b.assumptions.item9": `Broadly comparable age and baseline skin`,
  "s4b.assumptions.item10": `The two sunscreens differ hypothetically in actual photoprotection`,
  "s4b.disclaimer": `This is an illustrative conceptual model — not a measured clinical dataset for any specific sunscreen, person, or outcome.`,
  "s4b.src1": `Quan T, Fisher GJ. Gerontology. 2015. PMID 25660807`,
  "s4b.src2": `Randhawa M et al. Dermatol Surg. 2016. PMID 27749441`,
  "s4b.src3": `Boyd AS et al. J Am Acad Dermatol. 1995. PMID 7490363`,
  "s4b.src4": `Hughes MCB et al. Ann Intern Med. 2013. PMID 23732711`,
  "s5.eyebrow": `Skin Science`,
  "s5.title": `Why this matters more for South Asian skin`,
  "s5.lead": `The majority of Bangladesh's population falls within Fitzpatrick phototypes IV through VI, characterised by highly active melanocytes. When sunscreen fails to provide adequate protection for melanin-rich skin, the consequences extend beyond sunburn: specific biochemical pathways are activated that can produce persistent outcomes such as melasma and post-inflammatory hyperpigmentation.`,
  "s5.guide": `This section explains three distinct biological mechanisms that demonstrate why avoiding sunburn is not sufficient — and why the integrity of the sunscreen film is, in fact, the central question.`,
  "s5.card1.title": `Opsin-3 (OPN3) Pigmentation Pathway`,
  "s5.card1.text": `OPN3 is a receptor found in the melanocyte cells of skin. It responds to blue light (approximately 415 nm) and UVA radiation. When the sunscreen film is compromised or absent, greater quantities of this light reach the skin. OPN3 activation can sustain the activity of Tyrosinase — the enzyme central to melanin synthesis — potentially producing not merely transient sun-induced darkening, but persistent melasma or post-inflammatory pigmentation.`,
  "s5.card1.foot": `Source: Regazzetti et al., J Invest Dermatol, 2018; PNAS, 2019`,
  "s5.card2.title": `Visible Light — outside the scope of SPF`,
  "s5.card2.text": `Visible light (400–700 nm) constitutes approximately 45% of total solar irradiance. Neither SPF nor UVA-PF ratings account for protection against this portion of the spectrum. In Fitzpatrick skin types III through VI, visible light alone can induce more pronounced and persistent pigmentation than UVA1. The evidence-based intervention is the inclusion of iron oxide pigments in sunscreen formulations — the only ingredient demonstrated to reflect visible light effectively.`,
  "s5.card2.foot": `Source: Dumbuya et al., J Drugs Dermatol, 2020; JID Expert Consensus, 2026`,
  "s5.card3.title": `Post-Irradiation DNA Damage`,
  "s5.card3.text": `A 2015 study published in Science by Premi and Brash demonstrated that following UV exposure, a photochemical reaction involving melanin can continue to generate DNA lesions (CPDs) for several hours after the UV source is removed. These lesions are associated with carcinogenesis. For melanin-rich skin, this is of particular relevance: if sunscreen protection is compromised during the day, its biochemical consequences may continue to unfold after sunset.`,
  "s5.card3.foot": `Source: Premi & Brash, Science, 2015; 347:842–847`,
  "climate.eyebrow": `Bangladesh Climate`,
  "climate.title": `The Climate We Live In`,
  "climate.temp.label": `TEMPERATURE`,
  "climate.temp.unit": `°C`,
  "climate.humidity.label": `HUMIDITY`,
  "climate.humidity.unit": `%`,
  "climate.source": `Source: Bangladesh Meteorological Department`,
  "s6.eyebrow": `Evidence-Based Selection Framework`,
  "s6.title": `A Science-Based Sunscreen Selection Framework for Bangladesh's Climate`,
  "s6.lead": `Rather than selecting by country of origin or brand narrative, it is more rational to choose based on what a regulatory framework and formulation architecture can actually deliver. Each tier below is grounded in regulatory documentation and formulation science.`,
  "s6.guide": `Note the card highlighted in gold. It represents the formulation category with the strongest documented evidence for sustained protection in both indoor and outdoor environments.`,
  "s6.w1.ribbon": `Highest Film Durability`,
  "s6.w1.tier": `All conditions — particularly heavy perspiration and outdoor exposure`,
  "s6.w1.name": `Australian (TGA)`,
  "s6.w1.scope": `Indoors and outdoors · Beach · Field · Sport`,
  "s6.w1.reason": `To claim water resistance, a TGA-listed sunscreen must pass a specific water resistance test. Australia's stringent requirements compel formulators to develop formulations capable of maintaining the sunscreen film on skin under both sweat and water contact — making it more likely that protection is retained even during intense outdoor activity in heat. Government surveillance is an integral part of this system: if a product fails to meet standards, the TGA has both the authority and the institutional capacity to investigate and, where necessary, recall it from market.`,
  "s6.w1.t1": `4-hour water resistance`,
  "s6.w1.t2": `Government surveillance`,
  "s6.w1.t3": `Effective indoors and outdoors`,
  "s6.w2.ribbon": `Maximum UVA Coverage`,
  "s6.w2.tier": `All conditions — broadest spectrum protection`,
  "s6.w2.name": `European (Mexoryl 400 filter)`,
  "s6.w2.scope": `Indoors, office, commuting, extended outdoor exposure — all settings`,
  "s6.w2.reason": `Mexoryl 400, or Methoxypropylamino Cyclohexenylidene Ethoxyethylcyanoacetate (MCE), is a next-generation UV filter developed over approximately a decade of research. It provides particularly strong protection in the ultra-long UVA range of 380–400 nm — a band in which many conventional filters offer comparatively weak coverage. In formulations such as La Roche-Posay Anthelios UVMune 400, Mexoryl 400 is combined with additional UV filters. The proprietary Netlock technology further assists in forming a uniform, moisture-resistant layer on the skin surface — making such formulations effective not only outdoors but also in indoor environments where long-wave UVA can penetrate through window glass.`,
  "s6.w2.t1": `Mexoryl 400 / MCE`,
  "s6.w2.t2": `Netlock film technology`,
  "s6.w2.t3": `Ultra-long UVA coverage`,
  "s6.w3.tier": `Daily use / humid conditions`,
  "s6.w3.name": `Japanese (MHLW / JCIA)`,
  "s6.w3.scope": `Daily commuting · Office · Moderate outdoor exposure`,
  "s6.w3.reason": `Japanese sunscreens typically employ Water-in-Silicone (W/Si) emulsion architectures. The volatile silicone component evaporates after application, depositing a thin, water-resistant film on the skin surface that resists displacement by perspiration. JCIA's new ★/★★ water resistance rating system — being phased in progressively from 2022 to 2027 — provides a standardised basis for assessing water resistance claims.`,
  "s6.w3.t1": `W/Si emulsion`,
  "s6.w3.t2": `JCIA ★★ rating`,
  "s6.w3.t3": `PA++++ UVA coverage`,
  "s6.w4.tier": `Controlled environments / minimal perspiration`,
  "s6.w4.name": `Korean (MFDS)`,
  "s6.w4.scope": `Air-conditioned settings · Minimal outdoor exposure`,
  "s6.w4.reason": `Post-2020 Korean sunscreens typically prioritise lightweight, comfortable formulations — a design emphasis reflected in the output of major ODM manufacturers such as Kolmar Korea and Cosmax. Static SPF 50+ testing is conducted per ISO 24444. However, the lightweight formulation architecture carries a structural limitation: under significant perspiration, the film may re-emulsify, raising questions about sustained protection in high-sweat conditions. This is not a product quality deficiency — it is a deliberate formulation trade-off in favour of wearability, making these products most appropriate for controlled, low-sweat environments such as air-conditioned offices.`,
  "s6.w4.t1": `SPF 50+ verified (static)`,
  "s6.w4.t2": `Lightweight skin feel`,
  "s6.w4.t3": `Improved QC post-2020`,
  "s6.tint.head": `Important for melasma-prone skin across all tiers`,
  "s6.tint.body": `Regardless of which tier you select, verify that the ingredient list includes iron oxide pigments (tint) for protection against visible light (400–700 nm). Standard SPF and UVA-PF ratings do not cover the visible spectrum — yet visible light is the primary driver of pigmentation in Fitzpatrick types III–VI skin. Tinted sunscreens containing iron oxides represent the only evidence-based approach to blocking this pathway.`,
  "s6.tint.cite": `Source: Dumbuya et al., Journal of Drugs in Dermatology, 2020; Journal of Investigative Dermatology International Expert Consensus, 2026`,
  "s6.india.eyebrow": `Technical Observations`,
  "s6.india.title": `Technical observations on sunscreens from the South Asian regional market`,
  "s6.india.lead": `In the context of the regulatory comparisons presented above, several specific technical observations regarding the South Asian regional market — including India — are presented here. These address aspects not fully captured by the comparative table.`,
  "s6.india.r1.label": `Batch-to-batch consistency`,
  "s6.india.r1.text": `Satisfactory laboratory results at the time of product registration do not guarantee equivalent performance across subsequent production batches. CDSCO's framework relies on a static SPF test at registration, without documented mandatory retesting of each subsequent production batch in publicly available records. Changes in raw material suppliers, minor process modifications, or packaging-formula interactions over time can introduce variability in product performance.`,
  "s6.india.r2.label": `Regulatory classification differential`,
  "s6.india.r2.text": `In India, sunscreens are classified as "Schedule S Cosmetics" under the Drugs and Cosmetics Act — not the functional equivalent of Australia's "Therapeutic Medicine" classification. The practical implication is that manufacturing and control standards follow cosmetic-grade requirements, which are less stringent than pharmaceutical-grade GMP. This is a structural difference of which consumers should be aware — not, in itself, evidence of any specific product failure.`,
  "s6.india.r3.label": `Transparency of post-market surveillance`,
  "s6.india.r3.text": `Unlike Australia or South Korea — where product failures, investigations, recalls, and remedial actions are publicly documented (as in the 2025 Australian recall or the 2020 Korean Purito incident) — no government-initiated corrective action specifically addressing SPF label failures has been identified in India's public regulatory record. This does not imply that all products are substandard. It does mean that the information available to consumers for independent verification is comparatively limited.`,
  "s7.eyebrow": `References`,
  "s7.title": `Sources & Regulatory Documentation`,
  "s7.lead": `Every claim in this report is drawn from peer-reviewed scientific publications, official regulatory documentation, or independently verified consumer testing. No advertising or paid partnerships are involved.`,
  "s7.src1": `Sunscreen application — theory and practice. Photodermatol Photoimmunol Photomed. PubMed: 24313722`,
  "s7.src2": `Melanin chemiexcitation and delayed DNA damage. Science, 347:842–847`,
  "s7.src3": `Visible light-induced skin darkening and the role of iron oxide. J Drugs Dermatol`,
  "s7.src4": `SPF analysis of commercial sunscreens in the Bangladesh market. J Biosci Public Health, 2(3):264–277`,
  "s7.src5": `Australian Regulatory Guidelines for Sunscreens (ARGS); TGA updates, September 2025 & March 2026`,
  "s7.src6": `Standards for in vivo SPF determination and water resistance retention calculations`,
  "s7.src7": `Independent testing: 16 of 20 sunscreens failed SPF claims; TGA recall response`,
  "s7.src8": `SPF 50+ product tested at SPF 19 in independent European laboratory; subsequent regulatory correction`,
  "s7.src9": `Role of OPN3 in epidermal melanocytes and the melanogenesis cascade`,
  "s7.src10": `Generalised Beer-Lambert model for heterogeneous sunscreen films`,
  "s7.src11": `BIS IS 4707:2022; Indian government cosmetic regulatory framework`,
  "s7.src12": `First global consensus statement on visible light photoprotection`,
  "s8.kicker": `Special Report`,
  "s8.title": `Australian Sunscreen — Not Just a Product, but a Government Commitment`,
  "s8.entry.p1": `The "SPF 50" printed on a sunscreen bottle is, ultimately, a claim — unless a government stands behind it. In Australia's case, the government genuinely does. By law.`,
  "s8.entry.p2": `In most countries, sunscreen is classified as an ordinary cosmetic. In Australia, any sunscreen with an SPF of 4 or above is legally classified as a Therapeutic Good — the equivalent of a medicine.`,
  "s8.legalBadge": `TGA — the same government body that approves every medicine and vaccine in Australia`,
  "s8.contrast.world.header": `🌍 Rest of the World`,
  "s8.contrast.au.header": `🇦🇺 Australia`,
  "s8.contrast.row1.label": `Product Classification`,
  "s8.contrast.row1.world": `Standard cosmetic`,
  "s8.contrast.row1.au": `Legally a medicine`,
  "s8.contrast.row2.label": `Water Test Duration`,
  "s8.contrast.row2.world": `Maximum 80 minutes`,
  "s8.contrast.row2.au": `Up to 4 hours`,
  "s8.contrast.row3.label": `SPF Verification`,
  "s8.contrast.row3.world": `Company self-assessed`,
  "s8.contrast.row3.au": `Directly government-regulated`,
  "s8.contrast.row4.label": `Advertising Controls`,
  "s8.contrast.row4.world": `Weak or absent`,
  "s8.contrast.row4.au": `Misleading claims prohibited by law`,
  "s8.tests.heading": `Four mandatory tests before market entry`,
  "s8.tests.intro": `No company may simply bring a sunscreen to the Australian market. Before the TGA grants approval, every product must pass four independent tests.`,
  "s8.test1.title": `Direct SPF verification on human skin`,
  "s8.test1.summary": `Not on a machine — on a human back`,
  "s8.test1.body": `This test is conducted not on laboratory equipment, but directly on human volunteers. A minimum of ten participants have a defined quantity (2 mg/cm²) of sunscreen applied to their backs, after which a Solar Simulator delivers intense artificial UV radiation. The ratio between how quickly unprotected skin reddens and how long protected skin remains unaffected determines the true SPF. If the result cannot be proven on human skin in a laboratory setting, approval is not granted.`,
  "s8.test2.title": `Water resistance test`,
  "s8.test2.summary": `Holds through Dhaka's sweat — for 4 hours`,
  "s8.test2.body": `This is the most distinctive feature of Australian sunscreen regulation. Volunteers with sunscreen applied are immersed in a swimming pool — with active water movement. If the product maintains its protective efficacy after a defined period of immersion (2 hours or 4 hours), only then is the label claim "Water Resistant" permitted.`,
  "s8.test2.stat.number": `4`,
  "s8.test2.stat.label": `hours in water — Australia's maximum`,
  "s8.test2.stat.compare": `Maximum in other countries: 80 minutes`,
  "s8.test2.closing": `In Bangladesh's humid climate, where perspiration is a constant challenge, this test provides the most reliable evidence of a product's real-world efficacy.`,
  "s8.test3.title": `UVA protection verification (Broad Spectrum Test)`,
  "s8.test3.summary": `Not just sunburn — melasma protection too`,
  "s8.test3.body": `SPF measures protection against UVB — the cause of sunburn. Whether the product also blocks UVA radiation — which penetrates deeper into skin and is responsible for melasma and long-term photoageing — is tested separately. Under Australian regulations, a product must block radiation above 370 nm. Failure to pass this test prohibits sale.`,
  "s8.test4.title": `Thermal stability test`,
  "s8.test4.summary": `Intact at 50°C — engineered for Dhaka's heat`,
  "s8.test4.body": `To verify that product quality does not degrade under heat or prolonged storage, products are held at 40–50°C for several months. If the cream separates from its oils, or if efficacy declines, the product is rejected. This test is the reason Australian sunscreens remain effective even in Dhaka's extreme heat.`,
  "s8.surveillance.heading": `Government oversight does not stop at market entry`,
  "s8.surveillance.body": `Even after approval, every company remains subject to ongoing government surveillance. Factories are inspected regularly. False advertising claims carry licence revocation and substantial financial penalties.`,
  "s8.surveillance.prohibited.claims": `❌ "100% sun protection" · "No need to reapply all day"`,
  "s8.surveillance.prohibited.note": `— These categories of misleading claim are prohibited by law in Australia`,
  "s8.artg.label": `What to look for on the bottle`,
  "s8.artg.number": `AUST L — XXXXXXXX`,
  "s8.artg.explain": `Every approved product carries an ARTG number — a unique identifier registered in the government's central database. Its presence confirms that the product has arrived in your hands not merely from a factory, but with government approval.`,
  "s8.artg.link": `Verify on the TGA website ↗`,
  "s8.cc.heading": `Cancer Council — not a business, but a commitment`,
  "s8.cc.body": `The Cancer Council sunscreen is not the product of a commercial cosmetics company. It is produced by a government-supported non-profit organisation. A substantial portion of the revenue from its sale is directed directly to cancer research and treatment.`,
  "s8.cc.quote": `By purchasing this product, you are not only protecting your own skin — you are contributing to a scientific mission.`,
  "s8.usaaus.heading": `Why Australian filter technology leads the United States`,
  "s8.usaaus.us.header": `🇺🇸 United States (FDA)`,
  "s8.usaaus.us.item1": `No new filter approved in 25 years`,
  "s8.usaaus.us.item2": `Constrained to use legacy chemical filters`,
  "s8.usaaus.us.item3": `Tinosorb, Uvinul not approved`,
  "s8.usaaus.au.header": `🇦🇺 Australia (TGA)`,
  "s8.usaaus.au.item1": `Updated in step with Europe`,
  "s8.usaaus.au.item2": `Most advanced photostable filters approved`,
  "s8.usaaus.au.item3": `Tinosorb M, Tinosorb S, Uvinul A Plus ✓`,
  "s8.timeline.heading": `Four decades of national practice`,
  "s8.timeline.item1.dot": `1981`,
  "s8.timeline.item1.title": `The "Slip, Slop, Slap" campaign`,
  "s8.timeline.item1.body": `Shirt on, sunscreen on, hat on — the birth of a national public health movement.`,
  "s8.timeline.item2.dot": `40+`,
  "s8.timeline.item2.title": `Four decades of research and refinement`,
  "s8.timeline.item2.body": `An entire nation applying sunscreen daily — researching, testing, and refining formulations year after year.`,
  "s8.timeline.item3.dot": `Today`,
  "s8.timeline.item3.title": `The world's most mature formulation science`,
  "s8.timeline.item3.body": `This accumulated experience is why Australian formulation science today represents the highest standard in the world.`,
  "s8.bottle.heading": `What to look for when buying`,
  "s8.bottle.body": `Genuine TGA-approved sunscreens sold in the Australian market carry the marking AUST L — registration number in small type on the packaging. This number can be verified on the TGA's official website.`,
  "s8.bottle.closing": `When you hold a Cancer Council or Hamilton bottle, you can be confident that what is inside it was proven — in water and on human skin — before it reached your hands.`,
  "s8.citation": `Source: TGA Therapeutic Goods Administration · ABC News Australia · ChemLinked Cosmetic Regulatory Portal · CHOICE Australia · Clayton Utz Legal Analysis · Standard Procedure Australia · Mukti Organics Research · SBS Bangla · Nine.com.au Health`,
  "foot.brand": `Sunscreen Research`,
  "foot.metaYear": `2026`,
  "foot.tag": `Independent, evidence-based photoprotection education. No advertising or paid partnerships.`,
  "foot.discLabel": `Disclaimer`,
  "foot.disc": `This website is produced for educational purposes only and does not constitute medical advice. All regulatory information is sourced from official government documentation. For personalised guidance, consult a dermatologist. Charts and comparative illustrations are approximate visualisations derived from published research — not clinical outcome predictions.`,
  "foot.editLabel": `Editorial`,
  "foot.edit": `Every piece of text on this page is editable. See the editorial notes at the top of the content file.`,
};

export default content;
