export const content = {
  "brand.title": `Sunscreen Research`,
  "brand.sub": `FORMULATION &amp; REGULATORY REVIEW`,
  "hero.meta1": `<svg class="icon-sm" viewBox="0 0 24 24" stroke-width="1.5" fill="none" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></svg> Updated: August 2026`,
  "hero.meta2": `<svg class="icon-sm" viewBox="0 0 24 24" stroke-width="1.5" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7z"/><circle cx="12" cy="12" r="3"/></svg> Reading time: ~18 minutes`,
  "hero.meta3": `<svg class="icon-sm" viewBox="0 0 24 24" stroke-width="1.5" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><path d="M14 2v6h6M16 13H8M16 17H8M10 9H8"/></svg> Sources cited: 22`,
  "hero.kicker": `A Formulation Chemistry &amp; Regulatory Analysis`,
  "hero.title": `Your Sunscreen Says <em>SPF 50</em>. In Practice, How True Is That?`,
  "hero.p1": `In Bangladesh's climate — where the UV Index regularly exceeds 10, temperatures pass 35°C, and humidity stays above 80% — the gap between the number on a sunscreen bottle and its actual performance on skin can be enormous. How large? <strong>In independent testing of 30 sunscreens collected from the Bangladesh market, 93.3% failed to meet their labeled SPF claim.</strong>`,
  "hero.p2": `This report examines why that failure happens — through the lens of formulation chemistry, and through a comparative review of how different regulatory authorities address it. Every claim here is sourced.`,
  "hero.abstractLabel": `Abstract`,
  "hero.abstract": `How advanced a sunscreen's UV filter is only tells half the story of its real-world protection. The other half depends on whether the "film" carrying that filter — the layer formed on the skin's surface — survives sweat, sebum, and heat. This report separates these two distinct problems, and compares how different regulatory frameworks address the second one.`,
  "hero.byline.name": `Naeem Muhammad`,
  "hero.byline.stat1": `80 days of research`,
  "hero.byline.stat2": `100+ sources`,
  "hero.scroll": `scroll`,
  "toc.label": `Contents`,
  "toc.1": `Two Distinct Problems`,
  "toc.2": `Regulatory Comparison`,
  "toc.3": `Data in Numbers`,
  "toc.4": `Long-Term Effects`,
  "toc.5": `Dermatological Science`,
  "toc.6": `Selection Framework`,
  "toc.7": `Sources`,
  "toc.8": `Special Report`,
  "s1.eyebrow": `The Core Problem`,
  "s1.title": `One Number, Two Entirely Different Questions`,
  "s1.lead": `The SPF number printed on a sunscreen bottle is a result measured in a controlled laboratory. The question is — does that same result hold up on Bangladesh's streets, under the sun, through sweat? This section shows why the answer isn't always "yes."`,
  "s1.guide": `What you'll take from this section: why a sunscreen can have an excellent filter and still fail to protect in practice — and why that failure has nothing to do with the filter's quality.`,
  "s1.card1.title": `Question One — Photostability`,
  "s1.card1.text": `Does the filter molecule break down when hit by UV light, or does it stay intact? Modern filters like Bemotrizinol (Tinosorb S) and DHHB (Uvinul A Plus) are genuinely excellent here — they absorb UV and return to their resting state without degrading. Most advertising presents the answer to this one question as the whole story.`,
  "s1.card1.foot": `Source: Chaudhuri, Int J Cosmet Sci, 2001`,
  "s1.card2.title": `Question Two — Film Durability`,
  "s1.card2.text": `Does the layer carrying the filter actually stay on the skin? A perfectly photostable filter still gives zero protection if its film washes off or thins out. In Bangladesh's 35°C+ heat and 80%+ humidity, with heavy sweating, film survival is the real bottleneck — and that's governed by film-forming polymers and emulsion structure, not the filter.`,
  "s1.card2.foot": `Source: Keshavarzi et al., Skin Res Technol, 2022`,
  "s1.card3.title": `The Design Trade-off`,
  "s1.card3.text": `To create a "lightweight" feel, formulators often deliberately reduce film-forming polymers — because those polymers tend to leave a heavier or tackier finish. But those same polymers resist sweat wash-off. The design choice that makes a sunscreen feel "invisible" is often the same one that reduces its real-world durability.`,
  "s1.card3.foot": `Source: US Patent 5041281A; Cosmetics &amp; Toiletries Journal`,
  "s1.note.head": `The Physics — Why Even Good Filters Lose to Sweat`,
  "s1.note.body": `UV attenuation follows the Beer-Lambert law — A(λ) = ε·c·d, where "d" is film thickness. But the film formed on skin is never perfectly uniform — skin has pores, creases, and irregular texture. Ferrero &amp; Sohn (ACS Nano Letters, 2024) showed that when sweat causes "dewetting" — the film contracting into island-like patches — the near-zero-thickness zones disproportionately dominate UV transmission. The result: an SPF 50 sunscreen can effectively collapse to SPF 5, purely from geometric film rearrangement, with zero chemical degradation of the filter itself.`,
  "s1.note.cite": `Ferrero, L. &amp; Sohn, M. — "Generalized Beer-Lambert Law for Evaluating Heterogeneous Sunscreen Films" — ACS Nano Letters, 2024`,
  "s1.bd.head": `This Problem Has Been Directly Documented in Bangladesh's Own Market`,
  "s1.bd.body": `This isn't just theory from foreign research — it has been directly documented in Bangladesh's own market. A 2026 study (Haque et al., Journal of Biosciences and Public Health) independently tested 30 popular sunscreen products collected from the Bangladesh market. The finding was stark: 93.3% of the products tested delivered less protection than their labeled SPF claimed. In other words, the film-durability and regulatory-gap problems described in this report are not distant or theoretical — they are the everyday reality for Bangladeshi consumers.`,
  "s1.bd.cite": `Source: Haque et al., Journal of Biosciences and Public Health, 2026; 2(3):264–277`,
  "s2.eyebrow": `Regulatory Science`,
  "s2.title": `Four Regulatory Frameworks — An Objective Comparison`,
  "s2.lead": `Which country a sunscreen is approved in matters — not for nationalistic reasons, but because each framework sets different standards: how rigorous pre-market testing is, how water resistance is verified, what manufacturing quality looks like, and most importantly, what happens when a product fails. The data below comes directly from each country's official regulatory documents.`,
  "s2.guide": `Notice in this table: the Australia column is marked in green — because it is the only framework with actively government-run post-market surveillance, evidence for which is shown below.`,
  "s2.tbl.criterion": `Regulatory Criterion`,
  "s2.tbl.au": `Australia`,
  "s2.tbl.jp": `Japan`,
  "s2.tbl.eu": `European Union`,
  "s2.tbl.kr": `South Korea`,
  "s2.tbl.in": `India`,
  "s2.r1.label": `Product Classification`,
  "s2.r1.au": `Therapeutic Medicine`,
  "s2.r1.jp": `Quasi-Drug`,
  "s2.r1.eu": `Cosmetic (under strict EU rules)`,
  "s2.r1.kr": `Functional Cosmetic`,
  "s2.r1.in": `Schedule S Cosmetic`,
  "s2.r2.label": `Pre-Market SPF Testing`,
  "s2.r2.au": `Mandatory (ISO 24444)`,
  "s2.r2.jp": `Mandatory (JCIA standard)`,
  "s2.r2.eu": `Mandatory (Cosmetics Europe)`,
  "s2.r2.kr": `Precondition for approval`,
  "s2.r2.in": `One-time static test at registration`,
  "s2.r3.label": `Water Resistance Test Duration`,
  "s2.r3.au": `Up to 240 minutes (4 hours)`,
  "s2.r3.auSub": `per ISO 16217 + 18861`,
  "s2.r3.jp": `Up to 80 minutes (★★)`,
  "s2.r3.jpSub": `per ISO 18861:2020`,
  "s2.r3.eu": `80 minutes (very water resistant)`,
  "s2.r3.kr": `No separately mandated duration`,
  "s2.r3.in": `No mandated duration`,
  "s2.r4.label": `Manufacturing Standard (GMP)`,
  "s2.r4.au": `Pharmaceutical-grade (PIC/S)`,
  "s2.r4.jp": `High standard (quasi-drug GMP)`,
  "s2.r4.eu": `Cosmetic GMP (ISO 22716)`,
  "s2.r4.kr": `Major ODM-lab standard (Kolmar, Cosmax)`,
  "s2.r4.in": `General cosmetic-grade`,
  "s2.r5.label": `Post-Market Surveillance`,
  "s2.r5.au": `Active and ongoing — government-run`,
  "s2.r5.jp": `Strong — rapid action when issues surface`,
  "s2.r5.eu": `Strong — EU-wide market surveillance`,
  "s2.r5.kr": `Moderate — significantly strengthened post-2020`,
  "s2.r5.in": `Limited — no SPF-related recalls found in public record`,
  "s2.r6.label": `Key Standard References`,
  "s2.r6.au": `AS/NZS 2604:2021 · ISO 24444 · ISO 16217 · ISO 18861`,
  "s2.r6.jp": `JCIA guidelines · ISO 24444 · ISO 18861 (rollout 2022–2027)`,
  "s2.r6.eu": `Cosmetics Europe guidelines · EU Regulation 1223/2009`,
  "s2.r6.kr": `MFDS Functional Cosmetics Regulation · ISO 24444`,
  "s2.r6.in": `CDSCO Cosmetics Rules 2020 · BIS IS 4707:2022`,
  "s2.caption": `All data from official regulatory documents. Sources: TGA Australian Regulatory Guidelines for Sunscreens (ARGS); AS/NZS 2604:2021; MHLW Pharmaceutical and Medical Device Act; JCIA guidelines; MFDS Functional Cosmetics Regulation; CDSCO Cosmetics Rules 2020; BIS IS 4707:2022; ISO 24444:2019; ISO 18861:2020.`,
  "s2.au.head": `A Real Example of Rigorous Oversight`,
  "s2.au.body": `Sunscreen regulation in Australia is rigorous enough that when the consumer group CHOICE's independent June 2025 testing found 16 of 20 products failed to meet their claimed SPF, the government regulator TGA launched an immediate investigation. The outcome: 21 products sharing the same base formulation were formally recalled from the market and their listings cancelled. This demonstrates that sunscreen oversight in Australia isn't just on paper — the government actively monitors the sector and moves quickly on corrective action when failures surface. In March 2026, the TGA proposed even stricter new rules, including mandatory laboratory accreditation and data submission.`,
  "s2.au.cite": `Sources: CHOICE Australia, June 2025; Therapeutic Goods Administration official statements, September 2025 &amp; March 2026`,
  "s3.eyebrow": `Data in Numbers`,
  "s3.title": `Now Let's See What the Numbers Actually Say`,
  "s3.lead": `The two figures below are illustrative visualizations built from published peer-reviewed research — not any brand's claim or a clinical prediction, but a way to show the trend in published scientific data.`,
  "s3.guide": `The first figure shows how quickly protection drops when the applied amount is too low. The second shows the maximum water-resistance duration each regulatory framework tests for.`,
  "s3.c1.title": `Applied Amount vs. Actual Protection`,
  "s3.c1.sub": `Laboratory SPF testing applies 2.0 mg per square centimeter. In practice, most people apply only 0.4 to 1.0 mg. The effect of this gap isn't linear — it collapses sharply.`,
  "s3.c1.note": `Source: Petersen &amp; Wulf, Photodermatology Photoimmunology &amp; Photomedicine, 2014 (PubMed 24313722) — power-function dose-response model`,
  "s3.c2.title": `Maximum Water Resistance Tested, by Regulatory Framework`,
  "s3.c2.sub": `The maximum water-immersion duration each framework tests and permits to be claimed on a label. Bangladesh has no national sunscreen standard of its own.`,
  "s3.c2.note": `Sources: TGA AS/NZS 2604:2021; JCIA ISO 18861:2020 guidelines; EU Cosmetics Europe convention; CDSCO Cosmetics Rules 2020`,
  "s4.eyebrow": `Long-Term Effects`,
  "s4.title": `Now Let's See What Happens to Skin Over Years of Using a Given Sunscreen Type`,
  "s4.lead": `You won't see anything today from applying sunscreen — if you don't burn, it seems fine; if you do, it seems pointless. But the real damage happens invisibly, a little more every day. UV radiation accumulates deep in the skin — melasma, wrinkles, permanent changes — these appear suddenly 5 to 10 years later. By then, reversal is no longer possible. This is why sunscreen is a long-term investment: even when today's use shows no visible difference, it is determining what your skin looks like in the future.`,
  "s4.guide": `Below are two separate charts — one for UVA damage, one for UVB. Each shows three lines representing how much damage accumulates over years with High Quality, Mixed Quality, and Low Quality sunscreen use. The higher the line climbs, the more damage has accumulated.`,
  "s4.leg1": `High Quality (TGA) — Consistent, high water-resistant protection`,
  "s4.leg2": `Mixed Quality — average use`,
  "s4.leg3": `Low Quality — weak film durability or inconsistent batch quality`,
  "s4.leg1s": `High Quality`,
  "s4.leg2s": `Mixed Quality`,
  "s4.leg3s": `Low Quality`,
  "s4.uva.title": `UVA Damage — Accumulation Over Time`,
  "s4.uva.sub": `UVA rays reach the skin's deep layer (dermis), breaking down collagen and causing melasma. The damage is small each day but accumulates over years.`,
  "s4.uva.note": `Source: illustrative relative index based on Petersen &amp; Wulf (2014) dose-response model and published UVA penetration data`,
  "s4.uvb.title": `UVB Damage — Accumulation Over Time`,
  "s4.uvb.sub": `UVB rays burn the skin's outer layer (epidermis) and directly damage DNA. This is most strongly linked to skin cancer.`,
  "s4.uvb.note": `Source: illustrative relative index based on Petersen &amp; Wulf (2014) dose-response model and published UVB exposure data`,
  "s4.note": `These figures are an illustrative relative index built from Petersen &amp; Wulf's (2014) dose-response model and published data on sweat-driven film loss — not a clinical forecast for any individual.`,
  "s4.uv.label": `UVA & UVB — Two Distinct Threats`,
  "s4.uv.b.name": `The Burning Ray`,
  "s4.uv.b.list": `<li>Causes redness and sunburn</li><li>Damages the epidermis (outer skin layer)</li><li>Directly breaks DNA — primary cause of skin cancer</li><li>This is what SPF measures protection against</li>`,
  "s4.uv.b.reach": `Penetration depth: epidermis only`,
  "s4.uv.a.name": `The Silent Damage Ray`,
  "s4.uv.a.list": `<li>Doesn't cause sunburn — so you can't feel it</li><li>Reaches the dermis (deep skin layer)</li><li>Breaks down collagen — causes wrinkles and sagging</li><li>Primary cause of melasma and lasting pigmentation</li><li>Passes through window glass — works indoors too</li>`,
  "s4.uv.a.reach": `Penetration depth: into the dermis (far deeper than UVB)`,
  "s4.uv.note": `About 95% of solar UV radiation is UVA and 5% is UVB. UVA arrives consistently all day, every season, through clouds. SPF only measures UVB protection — look separately for PA+++ or UVA-PF ratings to assess UVA coverage.`,
  "s5.eyebrow": `Dermatological Science`,
  "s5.title": `Why This Matters Even More for South Asian Skin`,
  "s5.lead": `Most of Bangladesh's population has Fitzpatrick phototype IV through VI skin, with highly active melanocytes. In melanin-rich skin, a failed sunscreen film doesn't just risk sunburn — it triggers a biochemical pathway that causes sustained, often stubborn pigmentation problems.`,
  "s5.guide": `This section explains three distinct biological pathways that show why "just avoiding sunburn" isn't enough — film integrity is the real question.`,
  "s5.card1.title": `The Opsin-3 (OPN3) Pigmentation Pathway`,
  "s5.card1.text": `OPN3 is a receptor in skin melanocytes that responds to blue light (~415 nm) and UVA wavelengths. A weak or washed-off sunscreen film lets this light through, activating OPN3 through a calcium-dependent signaling cascade that keeps the pigment-producing enzyme Tyrosinase active for an extended period. The result isn't transient sunburn — it's sustained melasma or post-inflammatory pigmentation.`,
  "s5.card1.foot": `Source: Regazzetti et al., J Invest Dermatol, 2018; PNAS, 2019`,
  "s5.card2.title": `Visible Light — Outside What SPF Measures`,
  "s5.card2.text": `Roughly 45% of solar radiation is visible light (400-700nm). SPF and UVA-PF ratings do not measure protection against it. In Fitzpatrick III through VI skin, visible light alone can cause darker, more sustained pigmentation than UVA1. The evidence-based solution is iron oxide pigment in the sunscreen — the only ingredient shown to effectively reflect visible light.`,
  "s5.card2.foot": `Source: Dumbuya et al., J Drugs Dermatol, 2020; JID Expert Consensus, 2026`,
  "s5.card3.title": `DNA Damage That Continues After Sunset`,
  "s5.card3.text": `A 2015 study published in Science by Premi &amp; Brash showed that a chemical reaction in melanin continues generating harmful DNA changes (CPDs) — linked to cancer formation — for hours after UV exposure ends. This mechanism is particularly relevant in melanin-rich skin. In other words, if a sunscreen film fails during peak sun exposure, its impact can persist well into the night.`,
  "s5.card3.foot": `Source: Premi &amp; Brash, Science, 2015; 347:842–847`,
  "s6.eyebrow": `Evidence-Based Selection Framework`,
  "s6.title": `A Science-Based Selection Framework for Bangladesh's Climate`,
  "s6.lead": `Rather than choosing by country identity or brand story, it makes more sense to choose based on what a regulatory framework and formulation architecture can actually deliver. Each tier below is grounded in regulatory documents and formulation science.`,
  "s6.guide": `Notice the gold-marked card — it represents a formulation category shown to deliver the highest level of protection both indoors and outdoors.`,
  "s6.w1.ribbon": `Strongest film durability`,
  "s6.w1.tier": `ALL SETTINGS — ESPECIALLY HEAVY SWEAT &amp; OUTDOORS`,
  "s6.w1.name": `Australian (TGA)`,
  "s6.w1.scope": `Indoors &amp; outdoors · beach · fieldwork · sports`,
  "s6.w1.reason": `TGA-listed sunscreens must pass up to a 4-hour water-immersion test under pharmaceutical-grade standards before any water-resistance claim is allowed. This forces formulators to use high-level hydrophobic film-forming polymers — meaning the film holds through sweat, heat, or water. This is also why these sunscreens work equally well indoors: the film keeps UV filters anchored to skin in every condition, not just under outdoor heat. Government oversight is active enough that when a product fails, TGA identifies and recalls it from market itself.`,
  "s6.w1.t1": `4-hour water resistance`,
  "s6.w1.t2": `Government oversight`,
  "s6.w1.t3": `Indoor &amp; outdoor effective`,
  "s6.w2.ribbon": `Broadest UVA coverage`,
  "s6.w2.tier": `USABLE IN EVERY SETTING — MAXIMUM PROTECTION`,
  "s6.w2.name": `European (Mexoryl 400 Filter)`,
  "s6.w2.scope": `Indoors, office, commute, prolonged outdoor exposure — all of it`,
  "s6.w2.reason": `Methoxypropylamino Cyclohexenylidene Ethoxyethylcyanoacetate (Mexoryl 400, or MCE) is a next-generation filter — the result of roughly a decade of research and 25 patents — that extends protection to the very long end of the UVA spectrum (380-400nm), a range most conventional filters do not cover. This long-wave UVA penetrates deepest and is most strongly linked to melasma and long-term photoaging. In formulas like La Roche-Posay Anthelios UVMune 400, it's combined with Bemotrizinol (Tinosorb S) and Uvinul T150, and held in place by a "Netlock" film-forming technology that builds a uniform, humidity-resistant layer on skin. This is precisely why this formulation category performs equally well indoors — where UVA passes through window glass — and outdoors: it delivers the long-wave UVA protection every setting requires.`,
  "s6.w2.t1": `Mexoryl 400 / MCE`,
  "s6.w2.t2": `Netlock film technology`,
  "s6.w2.t3": `Ultra-long UVA coverage`,
  "s6.w3.tier": `DAILY USE / HUMID CONDITIONS`,
  "s6.w3.name": `Japanese (MHLW / JCIA)`,
  "s6.w3.scope": `Daily commuting · office · moderate outdoor exposure`,
  "s6.w3.reason": `Japanese sunscreens typically use Water-in-Silicone (W/Si) emulsion technology. Volatile silicones evaporate off the skin, leaving behind an ultra-thin, water-repellent silicone layer that resists breaking down on contact with sweat. The JCIA's newly mandatory ★/★★ water resistance rating system (fully rolling out 2022-2027) provides independent verification of these claims.`,
  "s6.w3.t1": `W/Si emulsion`,
  "s6.w3.t2": `JCIA ★★ rating`,
  "s6.w3.t3": `PA++++ UVA coverage`,
  "s6.w4.tier": `CONTROLLED ENVIRONMENT / LOW SWEAT`,
  "s6.w4.name": `Korean (MFDS)`,
  "s6.w4.scope": `Air-conditioned settings · minimal outdoor exposure`,
  "s6.w4.reason": `Post-2020 Korean sunscreens, made by major ODM manufacturers like Kolmar Korea or Cosmax, reliably meet their static SPF 50+ claims under ISO 24444. However, their typical O/W emulsion structure — deliberately chosen for a light, comfortable feel — tends to re-emulsify on contact with sweat. This isn't a quality flaw; it's a deliberate formulation trade-off suited to controlled, low-sweat environments.`,
  "s6.w4.t1": `SPF 50+ verified (static)`,
  "s6.w4.t2": `Lightweight feel`,
  "s6.w4.t3": `Improved QC post-2020`,
  "s6.tint.head": `Important Across Every Tier for Melasma-Prone Skin`,
  "s6.tint.body": `Whichever tier you choose, check the ingredient list for iron oxide pigment (tint) for protection against visible light (400-700nm). Standard SPF and UVA-PF ratings don't cover visible light — yet it's the primary driver of pigmentation in Fitzpatrick III-VI skin. Iron oxide in a tinted sunscreen is the only evidence-based way to block this pathway.`,
  "s6.tint.cite": `Source: Dumbuya et al., Journal of Drugs in Dermatology, 2020; Journal of Investigative Dermatology International Expert Consensus, 2026`,
  "s6.india.eyebrow": `A Related Review`,
  "s6.india.title": `Technical Observations on South Asian Regional-Market Sunscreens`,
  "s6.india.lead": `In light of the regulatory comparison above, here are some specific technical observations on South Asian regional-market sunscreens, including India — points that couldn't be shown separately in the comparison table above.`,
  "s6.india.r1.label": `Batch-to-Batch Consistency`,
  "s6.india.r1.text": `A sunscreen showing good laboratory results at registration doesn't mean every subsequent production batch maintains that same standard. CDSCO's framework relies on a static test at registration, but no publicly documented mandatory system exists for regularly re-testing each subsequent production batch. Changes in raw material suppliers, minor process shifts, or interactions between the formula and packaging can all introduce variation in final-product performance over time.`,
  "s6.india.r2.label": `Regulatory Classification Gap`,
  "s6.india.r2.text": `In India, sunscreens are classified as "Schedule S Cosmetics" under the Drugs and Cosmetics Act — not the equivalent of Australia's "Therapeutic Medicine" class. In practical terms, this means manufacturing and control systems follow cosmetic-grade standards, which are less rigorous than pharmaceutical-grade GMP. This is not, by itself, evidence that any specific product fails — it is a structural difference consumers should be aware of.`,
  "s6.india.r3.label": `Post-Market Transparency`,
  "s6.india.r3.text": `Unlike Australia or Korea, where a product's failure, recall, and correction process is publicly documented by the government (the 2025 Australian recall or the 2020 Korean Purito incident, for example), no publicly documented government corrective action for SPF-label failures could be found for India. This does not mean every product is substandard — it means the transparency of verifiable information available to consumers is comparatively lower.`,
  "s7.eyebrow": `Sources`,
  "s7.title": `Sources &amp; Regulatory Documents`,
  "s7.lead": `Every claim in this report is sourced from peer-reviewed scientific publications, official regulatory documents, or independently documented consumer testing. No advertising, no paid partnerships.`,
  "s7.src1": `Application of sunscreen — theory and reality. Photodermatol Photoimmunol Photomed. PubMed: 24313722`,
  "s7.src2": `Melanin chemiexcitation and delayed DNA damage. Science, 347:842–847`,
  "s7.src3": `Visible light-induced skin darkening and the role of iron oxide. J Drugs Dermatol`,
  "s7.src4": `SPF analysis of commercial sunscreens in the Bangladesh market. J Biosci Public Health, 2(3):264–277`,
  "s7.src5": `Australian Regulatory Guidelines for Sunscreens (ARGS); TGA updates, September 2025 &amp; March 2026`,
  "s7.src6": `In-vivo SPF determination and water resistance retention calculation standards`,
  "s7.src7": `16 of 20 sunscreens failed SPF claims in independent testing; TGA recall response`,
  "s7.src8": `SPF 50+ product tested at SPF 19 by independent European labs; subsequent regulatory correction`,
  "s7.src9": `Role of OPN3 in epidermal melanocytes and the melanogenesis cascade`,
  "s7.src10": `Generalized Beer-Lambert model for heterogeneous sunscreen films`,
  "s7.src11": `BIS IS 4707:2022; Government of India cosmetic regulatory framework`,
  "s7.src12": `First global consensus statement on visible-light photoprotection`,
  "s8.kicker": `Special Report`,
  "s8.title": `Australian Sunscreen — Not Just a Product, a Government Guarantee`,
  "s8.body": `<p>The words "SPF 50" printed on a sunscreen bottle are only a claim — unless a government stands behind that claim. In Australia's case, a government genuinely does. By law.</p>
<p>In most countries, sunscreen is a standard cosmetic product. In Australia, any sunscreen with SPF 4 or higher is legally classified as a "Therapeutic Good" — a medicine. Oversight responsibility falls to the Therapeutic Goods Administration (TGA), an independent body under the Department of Health — the same body that approves every drug and vaccine in Australia.</p>
<h3>Four Mandatory Tests Before Reaching the Market</h3>
<p>No company can simply sell sunscreen in Australia. The TGA requires every product to pass four separate tests before approval.</p>
<div class="s8-test"><strong>Test One — SPF Verified on Human Skin</strong><p>This test is not conducted on machines in a laboratory — it is performed directly on human subjects. At least ten volunteers have sunscreen applied at 2mg/cm² across their backs, then are exposed to intense artificial UV through a Solar Simulator. The ratio of how quickly skin reddens without sunscreen versus how long it holds with sunscreen determines the actual SPF. Whatever is printed on the bottle must be demonstrated on human skin to get approval.</p></div>
<div class="s8-test"><strong>Test Two — Water Resistance Test</strong><p>This is the defining feature of Australian sunscreens. Volunteers enter a swimming pool — with water current — and remain submerged for the claimed duration (2 or 4 hours). Only if protection holds afterward is the "Water Resistant" label permitted. Other countries cap this at 80 minutes. Australia allows claims up to 4 hours. In Bangladesh's humid climate, where sweat is constant, this test is the most reliable real-world performance evidence available.</p></div>
<div class="s8-test"><strong>Test Three — UVA Protection (Broad Spectrum Test)</strong><p>SPF only measures UVB protection — what causes sunburn. UVA rays, which penetrate deeper and are primarily responsible for melasma and long-term photoaging, are tested separately. Australian rules require sunscreen to block wavelengths beyond 370nm — failing this means no sale.</p></div>
<div class="s8-test"><strong>Test Four — Heat Stability Test</strong><p>Whether the product degrades under heat or long storage is tested by holding it at 40–50°C for several months. If the cream separates or loses efficacy, it is rejected. This is why Australian sunscreens remain effective in Dhaka's intense heat.</p></div>
<h3>Government Oversight Continues After Market Entry</h3>
<p>Every approved product carries an ARTG registration number on its bottle — a unique identifier in the government's central database. Factories face regular government inspections. Misleading advertising claims result in license cancellation and major fines. Claims like "100% sun protection" or "no reapplication needed" are legally prohibited in Australia.</p>
<h3>Cancer Council — Not a Business, a Commitment</h3>
<p>The Cancer Council sunscreen you see on shelves is not the product of a commercial cosmetics company. It belongs to a government-supported nonprofit organization. Revenue from sunscreen sales goes substantially toward cancer research and treatment. Buying this product means protecting your own skin while indirectly contributing to a scientific cause.</p>
<h3>Why Australian Filter Technology Leads</h3>
<p>The US FDA has approved no new sunscreen filters in 25 years, leaving American formulas dependent on older chemicals. Australia takes the opposite approach — allowing the most modern photostable filters available, including Tinosorb M, Tinosorb S, and Uvinul A Plus. These don't degrade under prolonged sun exposure and don't cause skin irritation.</p>
<h3>40 Years of National Habit</h3>
<p>In 1981, the Australian government launched the national "Slip, Slop, Slap" campaign — put on a shirt, apply sunscreen, wear a hat. For over four decades since, an entire nation has been applying sunscreen daily, researching it, and refining formulations. This historical depth of experience is precisely why Australian formulation science is among the most mature in the world.</p>
<h3>What to Look for on the Bottle</h3>
<p>Every genuine TGA-approved sunscreen sold in the Australian market carries <span class="s8-aust-id">AUST L — Registration Number</span> on its label. This number can be verified on TGA's official website. When you pick up a bottle of Cancer Council or Hamilton, you can be confident that what's inside was tested in water and on human skin before it reached your hands.</p>
<div class="s8-cite">Sources: TGA Therapeutic Goods Administration · ABC News Australia · ChemLinked Cosmetic Regulatory Portal · CHOICE Australia · Clayton Utz Legal Analysis · Standard Procedure Australia · SBS Bangla · Nine.com.au Health</div>`,
  "foot.brand": `Sunscreen Research`,
  "foot.tag": `Independent, science-based photoprotection education. No advertising, no paid partnerships.`,
  "foot.discLabel": `Disclaimer`,
  "foot.disc": `This website is for educational purposes only and does not constitute medical advice. All regulatory data is drawn from official government documents. Consult a dermatologist for personalized advice. Charts and comparisons are illustrative visualizations built from published research — not clinical predictions.`,
  "foot.editLabel": `Editing`,
  "foot.edit": `Every piece of text on this page is editable. See the editing guide near the top of the file.`,
};

export default content;
